### ISSUE TITLE
Solve flake8 issues

### ISSUE THREAD

**Issue by nosredna123** [LARS-Org/aws-common#22]
amg@CPUAmg:~/projects/new_arch/aws-common$ pipenv run flake8 .
./app_common/app_utils.py:33:23: E741 ambiguous variable name 'l'
./app_common/app_utils.py:76:1: F401 'pprint' imported but unused
./app_common/app_utils.py:76:1: E402 module level import not at top of file
./app_common/app_utils.py:77:1: E402 module level import not at top of file
./app_common/app_utils.py:140:1: F401 'os' imported but unused
./app_common/app_utils.py:140:1: E402 module level import not at top of file
./app_common/app_utils.py:141:1: F401 'platform' imported but unused
./app_common/app_utils.py:141:1: E402 module level import not at top of file
./app_common/app_utils.py:142:1: F811 redefinition of unused 'subprocess' from line 7
./app_common/app_utils.py:142:1: E402 module level import not at top of file
./app_common/app_utils.py:143:1: F811 redefinition of unused 'sys' from line 8
./app_common/app_utils.py:143:1: E402 module level import not at top of file
./app_common/base_lambda_handler.py:8:1: F401 'traceback' imported but unused
./app_common/base_lambda_handler.py:10:1: F401 'decimal.Decimal' imported but unused
./app_common/base_lambda_handler.py:70:89: E501 line too long (95 > 88 characters)
./app_common/base_lambda_handler.py:338:89: E501 line too long (127 > 88 characters)
./app_common/base_lambda_handler.py:434:89: E501 line too long (89 > 88 characters)
./app_common/base_lambda_handler.py:450:89: E501 line too long (95 > 88 characters)
./app_common/base_lambda_handler.py:451:89: E501 line too long (121 > 88 characters)
./app_common/dynamodb_utils.py:2:89: E501 line too long (95 > 88 characters)
./app_common/dynamodb_utils.py:24:89: E501 line too long (89 > 88 characters)
./app_common/dynamodb_utils.py:26:89: E501 line too long (91 > 88 characters)
./app_common/dynamodb_utils.py:30:89: E501 line too long (91 > 88 characters)
./app_common/dynamodb_utils.py:92:89: E501 line too long (93 > 88 characters)
./app_scripts/app_setup.py:2:77: W291 trailing whitespace
./app_scripts/app_setup.py:39:13: F541 f-string is missing placeholders
./app_scripts/app_setup_execution.py:2:77: W291 trailing whitespace
./app_scripts/app_setup_execution.py:119:89: E501 line too long (134 > 88 characters)
./setup.py:14:89: E501 line too long (96 > 88 characters)
./tests/test_app_common/test_app_config.py:4:1: F401 'pytest' imported but unused
./tests/test_app_common/test_app_config.py:79:89: E501 line too long (96 > 88 characters)
./tests/test_app_common/test_app_utils.py:24:89: E501 line too long (89 > 88 characters)
./tests/test_app_common/test_app_utils.py:44:89: E501 line too long (95 > 88 characters)
./tests/test_app_common/test_app_utils.py:58:89: E501 line too long (121 > 88 characters)
./tests/test_app_common/test_app_utils.py:142:89: E501 line too long (95 > 88 characters)
./tests/test_app_common/test_app_utils.py:176:89: E501 line too long (100 > 88 characters)
./tests/test_app_common/test_app_utils.py:197:89: E501 line too long (105 > 88 characters)
./tests/test_app_common/test_app_utils.py:204:89: E501 line too long (121 > 88 characters)
./tests/test_app_common/test_app_utils.py:216:89: E501 line too long (116 > 88 characters)
./tests/test_app_common/test_app_utils.py:299:1: F401 'pprint' imported but unused
./tests/test_app_common/test_app_utils.py:299:1: E402 module level import not at top of file
./tests/test_app_common/test_app_utils.py:300:1: E402 module level import not at top of file
./tests/test_app_common/test_app_utils.py:302:1: F811 redefinition of unused 'do_log' from line 6
./tests/test_app_common/test_app_utils.py:302:1: E402 module level import not at top of file
./tests/test_app_common/test_app_utils.py:343:33: F811 redefinition of unused 'call' from line 426
./tests/test_app_common/test_app_utils.py:345:89: E501 line too long (155 > 88 characters)
./tests/test_app_common/test_app_utils.py:356:33: F811 redefinition of unused 'call' from line 426
./tests/test_app_common/test_app_utils.py:424:1: F401 'subprocess' imported but unused
./tests/test_app_common/test_app_utils.py:424:1: E402 module level import not at top of file
./tests/test_app_common/test_app_utils.py:425:1: E402 module level import not at top of file
./tests/test_app_common/test_app_utils.py:426:1: F401 'unittest.mock.call' imported but unused
./tests/test_app_common/test_app_utils.py:426:1: E402 module level import not at top of file
./tests/test_app_common/test_app_utils.py:428:1: E402 module level import not at top of file
./tests/test_app_common/test_app_utils.py:492:89: E501 line too long (105 > 88 characters)
./tests/test_app_common/test_base_lambda_handler.py:4:1: F401 'pytest' imported but unused
./tests/test_app_common/test_base_lambda_handler.py:18:89: E501 line too long (96 > 88 characters)
./tests/test_app_common/test_base_lambda_handler.py:30:89: E501 line too long (99 > 88 characters)

**Comment by sellaro** [comment]
PR submitted: https://github.com/LARS-Org/aws-common/pull/23
