### ISSUE TITLE
Config aws-common project as a PyPI repository.

### ISSUE THREAD

**Issue by nosredna123** [LARS-Org/aws-common#26]
```
    # TODO: Include aws-common project in the PyPI repository.
```

https://github.com/LARS-Org/aws-common/blob/38d90defd89bf1c209634ac4d5a9db56a81bef28/app_scripts/app_install_reqs.py#L50

**Comment by sellaro** [comment]
Configuring `aws-common` as a PyPI repo will allow other packages and repos to include `aws-common` as a regular dependency for their projects. This will simplify the usage of `aws-common`, avoiding the packages that depend on it to install it from GitHub directly.

**Comment by sellaro** [comment]
On it.
